_target_: ca_diffusion.models.diffusion_autoencoder.DiffusionAutoencoder

encoder:
  _target_: ca_diffusion.modules.networks.diffusion.unet2d.Encoder
  channels_in: 3
  channels: 64
  channels_z: 4
  channel_mult: [2,4,4]
  num_blocks: 2
  attn_res: [4,-1]
  num_heads: 8
  qkv_bias: True
  qk_norm: True
  compile: True
  use_checkpoint: False

decoder:
  _target_: ca_diffusion.modules.networks.diffusion.unet2d.UNet
  channels_in: 3
  channels: 64
  channels_emb: 512
  channel_mult: [2,4,4,8]
  num_blocks: 2
  attn_res: [4,-1]
  num_heads: 8
  qkv_bias: True
  qk_norm: True
  channels_freq: 256
  compile: True
  use_checkpoint: False
  channels_injection: 4
  injection_res: 4

diffusor:
  _target_: ca_diffusion.modules.diffusion.FlowMatching

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4
  weight_decay: 0.0

image_mode: True
