_target_: ca_diffusion.models.diffusion.LatentDiffusionModel

first_stage_ckpt: ???

model:
  _target_: ca_diffusion.modules.networks.diffusion.dit.DiT
  channels_in: 24
  channels: 768
  channels_emb: 1024
  channels_out: 24
  depth: 12
  num_heads: 12
  qk_norm: True
  expand: 4
  dropout: 0.0
  compile: True
  use_checkpoint: False
  channels_freq: 256
  patch_size: [1,1,1]
  shape: [16,16,16]
  num_register_token: 0

diffusor:
  _target_: ca_diffusion.modules.diffusion.FlowMatching

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4
  weight_decay: 0.0

precomputed_latents: False
