tensorboard:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  name: tensorboard
  save_dir: "${paths.output_dir}/tensorboard/"
  version: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
  sub_dir: null