defaults:
  - _self_
  - data: neurofinder_image
  - model: unsupervised_ca_image_diffusion
  - trainer: default
  - flags: default
  - paths: default
  - hydra: default
  - experiment: null

seed: 42
batch_size: 4

tag: default
ckpt_path: null
